/* Generated by scripts/generate-card-thumbs.js — do not edit by hand.
   original src -> [thumbnail src, thumbnail width, original width] */
const CARD_THUMBS = {
  "assets/img/projects/behance/d2logistics-email-design/full-design-preview.jpg": [
    "assets/img/card-thumbs/projects/behance/d2logistics-email-design/full-design-preview.webp",
    700,
    900
  ],
  "assets/img/projects/behance/cliqpiq-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/cliqpiq-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/orange-drink-social-media-post-design/01.jpg": [
    "assets/img/card-thumbs/projects/behance/orange-drink-social-media-post-design/01.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/orange-drink-social-media-post-design/02.jpg": [
    "assets/img/card-thumbs/projects/behance/orange-drink-social-media-post-design/02.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/orange-drink-social-media-post-design/03.jpg": [
    "assets/img/card-thumbs/projects/behance/orange-drink-social-media-post-design/03.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/orange-drink-social-media-post-design/04.jpg": [
    "assets/img/card-thumbs/projects/behance/orange-drink-social-media-post-design/04.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/dog-jacks-brand-identity/11.jpg": [
    "assets/img/card-thumbs/projects/behance/dog-jacks-brand-identity/11.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/dog-jacks-brand-identity/08.jpg": [
    "assets/img/card-thumbs/projects/behance/dog-jacks-brand-identity/08.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/dog-jacks-brand-identity/03.jpg": [
    "assets/img/card-thumbs/projects/behance/dog-jacks-brand-identity/03.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/dog-jacks-brand-identity/04.jpg": [
    "assets/img/card-thumbs/projects/behance/dog-jacks-brand-identity/04.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/neurahire-logo-design/29.jpg": [
    "assets/img/card-thumbs/projects/behance/neurahire-logo-design/29.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/skugistics-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/skugistics-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/dogford-email-design/full-design-preview.jpg": [
    "assets/img/card-thumbs/projects/behance/dogford-email-design/full-design-preview.webp",
    700,
    900
  ],
  "assets/img/projects/behance/water-supply-logo/01.webp": [
    "assets/img/card-thumbs/projects/behance/water-supply-logo/01.webp",
    1000,
    1400
  ],
  "assets/img/projects/behance/creative-nature-logo-design/02.webp": [
    "assets/img/card-thumbs/projects/behance/creative-nature-logo-design/02.webp",
    1000,
    1400
  ],
  "assets/img/projects/behance/creative-nature-logo-design/03.webp": [
    "assets/img/card-thumbs/projects/behance/creative-nature-logo-design/03.webp",
    1000,
    1400
  ],
  "assets/img/projects/behance/creative-solar-logo-design/01.webp": [
    "assets/img/card-thumbs/projects/behance/creative-solar-logo-design/01.webp",
    1000,
    1400
  ],
  "assets/img/projects/behance/creative-solar-logo-design/03.webp": [
    "assets/img/card-thumbs/projects/behance/creative-solar-logo-design/03.webp",
    1000,
    1400
  ],
  "assets/img/projects/bakara-management-cover.png": [
    "assets/img/card-thumbs/projects/bakara-management-cover.webp",
    1000,
    1440
  ],
  "assets/img/projects/startup-ready-cover.jpg": [
    "assets/img/card-thumbs/projects/startup-ready-cover.webp",
    1000,
    1280
  ],
  "assets/img/projects/behance/stewardshq-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/stewardshq-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/passelterra-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/passelterra-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/prune-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/prune-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/ticketbliss-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/ticketbliss-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/ame-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/ame-brand-identity/cover.webp",
    1000,
    1600
  ],
  "assets/img/projects/behance/hirearchical-brand-identity/cover.jpg": [
    "assets/img/card-thumbs/projects/behance/hirearchical-brand-identity/cover.webp",
    1000,
    1600
  ]
};
